// WARNING: This file is autogenerated, any changes will be overwritten.
export async function mdContent() {
  return [
    await import("../../content/lorem.md?raw"),
    await import("../../content/lorem2.md?raw"),
  ];
}
